install.packages("Microsoft365R")

library("Microsoft365R")



##
## creating a new email
##
# a blank text email
em <- outl$create_email()
# add a body
em$set_body("Hello from R", content_type="html")
# add recipients
em$set_recipients(to="user@example.com")
# add subject line
em$set_subject("example email")
# add an attachment
em$add_attachment("mydocument.docx")
# add a shareable link to a file in OneDrive
mysheet <- get_personal_onedrive()$get_item("documents/mysheet.xlsx")
em$add_attachment(mysheet)
# add an inline image
em$add_image("myggplot.jpg")
# oops, wrong recipient, it should be someone else
# this removes user@example.com from the to: field
em$set_recipients(to="user2@example.com")
# and we should also cc a third user
em$add_recipients(cc="user3@example.com")

# send it
em$send()
# you can also compose an email as a pipeline
outl$create_email()$
  set_body("Hello from R")$
  set_recipients(to="user2@example.com", cc="user3@example.com")$
  set_subject("example email")$
  add_attachment("mydocument.docx")$
  send()
# using blastula to create a HTML email with Markdown
bl_msg <- blastula::compose_email(md(
  "
## Hello!
This is an email message that was generated by the blastula package.
We can use **Markdown** formatting with the `md()` function.
Cheers,
The blastula team
"),
  footer=md("Sent via Microsoft365R"))
outl$create_email()
set_body(bl_msg)$
  set_subject("example blastula email")



library("Microsoft365R")

outlb <- get_personal_outlook()

outlb

## creating a new email
##
# a blank text email
em <- outlb$create_email()
# add a body
em$set_body(texto)
# add recipients
em$set_recipients(to=email)
# add subject line
em$set_subject("Relatório Mensal NAVV")
# add an attachment
em$add_attachment(filename_pdf)
# add an inline image

# send it
em$send()
# you can also compose an email as a pipeline

em
